services:
  - type: web
    name: atticusmini
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_BYBIT_TESTNET
        value: "false"
